Co-Drive/Driver-Client

src/common/CommonInput.tsx
- close #25 
- 마진이랑 텍스트 정렬만 수정한거라 크게 봐야할 내용은 없습니댱 !!
=> [ Common ] 공통 input 컴포넌트 바뀐 스타일 적용

src/components/Follower/FollowerRecommendCard.tsx, src/page/FollowerPage.tsx
- close #53 
https://github.com/user-attachments/assets/dbac4053-d405-4134-989f-d47b7c876a22
- 디자인 상 스크롤 표시가 없어서 스크롤은 가능하지만 화면에 스크롤 바는 보이지 않도록 구현했습니다.
```css
-ms-overflow-style: none; /* 인터넷 익스플로러 */
scrollbar-width: none; /* 파이어폭스 */
&::-webkit-scrollbar {
display: none;
}
```
<br />
- 스크롤이 들어가야 하는 요소에 id를 지정해서 해당 부분에 스크롤이 적용되도록 구현했습니다!
- `왼쪽`으로 이동
- scrollTo에 left:0을 줘서 왼쪽으로 이동시켰습니당
- behavior: 'smooth'     // 부드럽게 이동
```typescript
const handleClickIcLeft = () => {
const cardsContainer = document.getElementById('cardsContainer');
if (cardsContainer)
cardsContainer.scrollTo({ left: 0, behavior: 'smooth' });
};
```
- `오른쪽`으로 이동
- left에 scrollWidth - clientWidth 값을 주어, 숨겨진 영역만큼 왼쪽으로 스크롤을 당겨 오른쪽 끝으로 이동하도록 구현했습니다!
- **scrollWidth**: scroll할 수 있는 숨겨진 영역을 합한 width
- **clientWidth**: …
=> [ Follower ] 팔로워 추천 카드 퍼블리싱

src/App.tsx, src/assets/icon/thumbnail.svg, src/assets/index.ts, src/page/GroupComplete.tsx, src/types/GroupComplte/CompleteType.tsx
- close #41 
1️⃣ **[ 그룹 생성 페이지 바로가기 유지보수 용이하게 하기 ]** 
나중에 useNavigator 를 사용해서 바로 가게끔 할테니 코드를 이렇게 짜는게 맞지 않을까 ? 란 생각으로 코드를 작성하였습니다.
```tsx
const handleGroupPageRedirect = () => {
alert('그룹 페이지를 생성하고 유지보수 예정.');
navigate('/group-page'); // 그룹 페이지 생성 후 유지보수 예정
};
<CommonButton
onClick={handleGroupPageRedirect}
category="group_direct"
isActive={true}
/>
```
2️⃣ **[ 사용자 썸네일 이미지 받아오기 ]**
음.. 사용자가 만약에 그룹생성 페이지에서 이미지를 올리면 그룹 생성 완료 페이지에서는 그에 맞는 이미지를 렌더링 해줘야하고, 아니면 기본 이미지를 렌더링 해야 하는데 이걸 state를 사용해야하나.. 
음.. 굳이 state를 사용해서 변경할 필요 없고 props를 전달해서 사용하는게 좋다고 생각하여 작성하였습니다 ! 
나중에 서버에서 주는 URL 을 여기다가 업로드 하면 되겠다는 생각을 함 ! 
```jsx
const GroupComplete = ({ thumbnailUrl }: { thumbnailUrl: string }) => {
<ThumbnailContainer>
{thumbnailUrl ? (
) : (
<Thumbnail />
)}
</ThumbnailContainer>
}
```
```jsx
import …
```
=> [ Group ] 그룹생성하기 - 비밀그룹 완료 퍼블리싱

src/Router.tsx, src/components/Follower/CurrentSituation/SolvedQuestionModal.tsx, src/components/Follower/FollowerInfo.tsx, src/components/Solution/Header/SolutionHeaderBottom.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx, src/components/Solve/Header/CodeSpaceHeader.tsx, src/components/Solve/Header/HeaderTop.tsx, src/components/Solve/Header/PageHeader.tsx, src/libs/apis/Solution/getRecords.ts, src/libs/apis/Solve/patchRecords.ts, src/libs/apis/Solve/postRecords.ts, src/page/SolutionPage.tsx, src/page/SolvePage.tsx, src/types/Solution/solutionTypes.ts, src/types/Solve/solveTypes.ts, src/utils/fetchRecords.ts, src/utils/handleClickLink.ts
=> [ Deploy ] Feat/solve -> develop 머지

src/components/Register/Gitbhub.tsx, src/components/Register/IntroInput.tsx, src/components/Register/Language.tsx, src/components/Register/NickName.tsx, src/components/Register/SelectBox.tsx, src/page/RegisterPage.tsx, src/types/Register/RegisterType.tsx, src/utils/handleInput.ts
- close #31 
https://github.com/user-attachments/assets/602d22cb-d2e4-42ce-abe9-9ea93efe70fa
```
const RegisterPage = () => {
return (
<PageLayout category={'login'}>
<RegisterContainer onSubmit={handleJoinBtnClick}>
<NickName
nickname={nickname}
handleChangeInputs={handleChangeInputs}
handleNicknameCheck={handleNicknameCheck}
/>
<Language
selectedTag={selectedLanguage}
handleChangeTag={handleChangeTag}
/>
<IntroInput value={intro} maxLength={30} onChange={handleChangeIntro} />
<Github github={github} handleChangeInputs={handleChangeInputs} />
<RegisterButton>
<CommonButton
isActive={isActive}
category="account_create"
onClick={() => handleJoinBtnClick()}
/>
</RegisterButton>
</RegisterContainer>
</PageLayout>
);
};
```
```
useEffect(() => {
const isFormValid = 
nickname.length > 0 && …
```
=> [ Register ] 회원가입 뷰 퍼블리싱

src/common/Modal/Modal.tsx, src/common/Modal/SaveModalForm.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx, src/components/Solution/List/Calendar.tsx, src/components/Solution/List/ListFilter.tsx, src/components/Solution/List/SavedSolutionList.tsx, src/components/Solution/List/TempSave.tsx, src/components/Solve/Header/PageHeader.tsx, src/constants/Solve/SolveConts.ts, src/libs/apis/Solution/deleteRecords.ts, src/libs/apis/Solution/getMonthlySolution.ts, src/libs/apis/Solution/getTempRecords.ts, src/libs/apis/Solution/getUnsolvedMonths.ts, src/libs/apis/Solve/postTempRecords.ts, src/page/SolutionListPage.tsx, src/page/SolvePage.tsx, src/types/Solution/solutionTypes.ts, src/types/Solve/solveTypes.ts
- close #95 
https://github.com/user-attachments/assets/ca4e3490-f73d-4f92-870a-b50a0a33b6c2
https://github.com/user-attachments/assets/57a574a0-6792-451b-83ee-ab29ff34b951
- 요 api를 실행시키는 위치에 대해 고민이 많았는데요, 디자인과 상의한 결과 현재 모달에 있는 라이팅 수정 -> 나가기 버튼을 눌렀을 때 통신이 이뤄지는 것으로 이야기했습니당 ~!
- 공통 모달이기 때문에 props는 nullable로 설정했고, 문제 풀이 관련 데이터가 들어온 경우에만 post가 실행되도록 조건을 걸어줬어요
```typescript
const handleClickExitBtn = async () => {
if (questionInfo && codeblocks) {
try {
const { data } = await postTempRecords({
questionInfo: questionInfo,
codeblocks: codeblocks,
});
if (data) {
navigate('/solution');
onClose && onClose();
}
} catch (err) {
console.log(err);
}
}
};
```
<br />
- 임시 저장된 문제 풀이를 가져오는 과정에서 response로 받은 값들로 전체 페이지 수와 임시저장된 내용들을 업데이트 해주었어요
- 서버 통신에서 계속 에러가 나길래 물어봤더니, 서버에서는 페이지가 0부터 시작한다고 하더라구요! 그래서 선택된 …
=> [ Solution ] 임시저장 관련 로직 및 api 연결

src/Router.tsx, src/common/CommonInput.tsx, src/components/Register/Gitbhub.tsx, src/components/Register/IntroInput.tsx, src/components/Register/Language.tsx, src/components/Register/NickName.tsx
- close #121 
- 최종 뷰 디자인을 반영하여 스타일들을 수정했습니다!
=> [ Register ] 회원가입 뷰 퍼블리싱 수정

package.json, src/assets/icon/ic_nothing.svg, src/assets/icon/ic_workbook_black.svg, src/assets/index.ts, src/components/Follower/Current/AdditionalProblemsModal.tsx, src/components/Follower/Current/CurrentGraph.tsx, src/components/Follower/Current/CustomTooltip.tsx, src/components/Follower/Current/EmptyFollower.tsx, src/components/Follower/Current/EmptySolver.tsx, src/components/Follower/Current/FollowerCurrentGraph.tsx, src/components/Follower/Current/FollowerList.tsx, src/components/Follower/Current/FollowerQuestions.tsx, src/components/Follower/Current/NumOfQuestions.tsx, src/components/Follower/Current/Solver.tsx, src/components/Follower/Current/TodaysSolver.tsx, src/components/Follower/Current/WeeklyCurrentGraph.tsx, src/components/Follower/Personal/FollowerRecommendCard.tsx, src/components/Follower/Personal/ParticipatingGroup.tsx, src/constants/Follower/currentConst.ts, src/page/FollowerCurrentPage.tsx, src/page/FollowerPage.tsx, src/types/Follower/Current/currentType.ts, src/types/Follower/Personal/personalType.ts, yarn.lock
- close #139 
https://github.com/user-attachments/assets/88e5105d-1a95-4ff5-97a6-aab97612905c
- 라이브러리 사용 이유
- react와 호환이 잘 되고 커스텀이 쉬운 라이브러리를 위주로 고민했습니다.
- [react-chartjs-2](https://www.npmjs.com/package/react-chartjs-2) vs [recharts](https://www.npmjs.com/package/recharts)
- 비교적 최근까지 업데이트도 되었고 기본적으로 제공하는 그래프도 많은 recharts를 선택했습니다.
<br />
- 바탕이 될 그래프와 성과율을 나타낼 그래프 두 개를 겹쳐놓는 구조로 구현했습니다.
- 성과율을 나타낼 글자는 position absolute로 설정하여 그래프 안에 위치시켰습니다.
=> [ Follower ] 팔로워 현황 뷰 그래프 추가

package.json, src/components/Calendar/Calendar.tsx, src/components/Calendar/CustomCalendar.tsx, src/page/Home.tsx, yarn.lock
- close #124 
https://github.com/user-attachments/assets/2335be8b-63fd-43f9-bda1-c329046dc7f6
아직 스타일적인 부분만 해놨습니다 ! 홈 뷰 퍼블리싱이 전체 다 끝난 후 api 연결할 떄 한번에 작업을 다 할 예정입니다.
좀 오래걸린 이유가 기존의 있던 Calendar 컴포넌트를 재사용해서 사용할지 아니면 라이브러리에서 제공하는 NavBar를 개조해서 사용할지 둘 다 적용을 해보느라 오래 걸리기도 하였습니다. 또한 CSS 적용하는것도 많이 찾아보고 해매다보니 시간이 조금 지체되었습니다. 
```jsx
<StyledCalendar
onChange={setSelectedDate} // 바뀌는 날짜
locale="ko-KR" // 언어 선택
value={selectedDate} // 선택된 날짜
showNeighboringMonth={true} // 이웃된 달의 날짜 보여주기
formatShortWeekday={(_, date) => customWeekdays[date.getDay()]} // Weekday 를 표시해주는 역할
showNavigation={false} // 기본 NavBar 표기
/>
```
[참고사이트1️⃣](https://blog.logrocket.com/react-calendar-tutorial-build-customize-calendar/)
[참고사이트2️⃣](https://velog.io/@jh100m1/react-calendar-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%9E%A5%EC%9E%A5-7%E …
=> [ Common ] 캘린더 컴포넌트 퍼블리싱 뷰

package.json, src/components/Calendar/Calendar.tsx, src/components/Calendar/CustomCalendar.tsx, src/page/Home.tsx, yarn.lock
=> [ deploy ] Common 컴포넌트 머지 작업

src/Router.tsx, src/common/Modal/Modal.tsx, src/components/GroupDetail/ApplicationModal.tsx, src/components/GroupDetail/GroupInfo.tsx, src/components/GroupDetail/Header.tsx, src/libs/apis/GroupDetail/getDetail.ts, src/libs/apis/GroupDetail/getRequests.ts, src/libs/apis/GroupDetail/postPublicRequest.ts, src/libs/hooks/GroupDetail/useGetDetail.ts, src/libs/hooks/GroupDetail/useGetRequests.ts, src/libs/hooks/GroupDetail/usePostPublicRequest.ts, src/page/GroupDetail.tsx, src/types/GroupDetail/groupDetailType.ts
=> Feat/group detail -> develop 머지

src/assets/icon/ic_warning.svg, src/assets/index.ts, src/common/Modal/ErrorModal/ErrorModal.tsx, src/common/Modal/ErrorModal/ErrorModalForm.tsx, src/common/Modal/WarningModal/WarningMoalForm.tsx, src/common/Modal/WarningModal/WarningModal.tsx, src/types/Modal/modalType.ts
=> [ Common ] 경고/ 에러 모달

src/assets/icon/ic_warning.svg, src/assets/index.ts, src/common/Modal/ErrorModal/ErrorModal.tsx, src/common/Modal/ErrorModal/ErrorModalForm.tsx, src/common/Modal/WarningModal/WarningMoalForm.tsx, src/common/Modal/WarningModal/WarningModal.tsx, src/types/Modal/modalType.ts
=> [ Deploy ] Feat/common -> develop 머지

src/Router.tsx, src/assets/icon/ic_filter.svg, src/assets/icon/ic_group_filter.svg, src/assets/icon/ic_search.svg, src/assets/index.ts, src/components/GroupAll/GroupItem.tsx, src/components/GroupAll/GroupRecommend.tsx, src/components/GroupAll/groupFilter/LanguageSelectBox.tsx, src/components/GroupAll/groupFilter/RangeSlidrFilter.tsx, src/components/GroupAll/groupFilter/SearchBar.tsx, src/constants/GroupAll/groupAllConst.ts, src/page/GroupAllPage.tsx, src/types/GroupAll/GroupAllType.tsx
- close #174 
https://github.com/user-attachments/assets/b58719c2-0ebd-4623-a048-7d5965e1b4c7
검색창, 태그, 슬라이더 필터 구현 완료
- 입력창이 비워지면 모든 그룹 데이터를 반환하게 구현했습니다.
- 입력된 검색어에 따라 필터링 기능을 구현했습니다. (이 부분도 더미데이터 기준)
- 그룹 제목, 소개, 닉네임, 태그, 멤버 수/총인원 검색할 수 있게 해뒀습니다.
```
if (newValue.trim() === '') {
// 입력창이 비워지면 모든 그룹 데이터를 반환
onSearch(GROUPS);
return;
}
```
- 승택이가 구현한 selectBox에선 all 태그를 눌렀을 시 all이라는 string을 제외한 모든 언어들이 들어가게 구현해 놨더라구요. 근데 저는 사용자가 all태그를 선택했을 때 그룹 tags 배열에 all 태그가 있으면 그 그룹만 반환해주면 되기 때문에 코드를 조금 변경 했습니다!
```
const filterGroups = () => {
return GROUP_ALL_DUMMY.group.filter((group) => {
// ALL_TAG가 선택된 경우, 그룹의 태그에 ALL_TAG가 포함되어 있으면 무조건 매칭
const isAllTagSelected = selectedTags.includes(ALL_TAG);
const groupHasAllTag = group.tags.includes(ALL_TAG); 
// 태그 필터링
const tagMatch =
selectedTags.length …
```
=> [ Group-All ] 그룹 뷰 수정 (디자인 반영)

src/common/CommonMonthSolve.tsx, src/components/Follower/FollowerInfo.tsx, src/components/Follower/Personal/Graph/CustomLabel.tsx, src/components/Follower/Personal/Graph/SuccessRate.tsx, src/libs/apis/Home/getMonthSolve.ts, src/libs/hooks/Home/useGetMonthSolve.ts, src/page/FollowerPage.tsx, src/page/Home.tsx, src/page/SolvePage.tsx, src/types/Home/getMonthSolveTypes.ts, src/utils/handleClickGoTopBtn.ts
=> [ Deploy ] Feat/profile -> develop merge

src/common/CommonMonthSolve.tsx, src/common/Header.tsx, src/components/Calendar/Calendar.tsx, src/components/Home/HomeHeader.tsx, src/components/Home/TodaySolve.tsx, src/components/Home/WeekRate.tsx, src/components/PageLayout/PageLayout.tsx, src/page/SolvePage.tsx
- close #issue_number
- Header Fixed 값 주기 ✅
- Header 마진 값 수정 ✅
- 오늘 문제풀이와 툴팁 사이 마진값 수정 ✅
- 캘린더 NavBar 마진값 수정 ✅
- 캘린더와 NavBar 사이 마진값 수정 ✅
- 캘린더 시작일 일요일로 변경 ✅
- 캘린더 요일 위아래 margin값 부여 ✅
- HomeHeader ID 부분 userId에 맞게 수정 ✅
- 캘린더 NavBar 클릭 된 월에 따라 (**월 문제풀이 현황) 변경되게 수정 ✅
- 오늘 문제풀이 및 주간 성과율 툴팁 박스 max-width 값 수정 및 <br/> 태그 삭제 ✅
=> [ Qa-5wintaek ] Home 부분 QA 반영

src/common/RecommendCard.tsx, src/components/GroupDetail/GroupInfo.tsx, src/components/GroupDetail/Header.tsx, src/components/GroupMember/GroupInfo.tsx, src/constants/utils/allTag.ts, src/libs/apis/GroupDetail/postPublicRequest.ts, src/libs/hooks/GroupDetail/usePostPublicRequest.ts, src/page/GroupDetail.tsx
=> [ Hotfix ] 빠르게 반영해야 하는 부분 수정

src/common/CommonMonthSolve.tsx, src/common/CommonUserList.tsx, src/common/Header.tsx, src/common/InformationTooltip.tsx, src/common/Modal/ErrorModal/ErrorModalForm.tsx, src/common/Modal/SaveCheckModal/SaveCheckModal.tsx, src/common/Modal/SaveCheckModal/SaveCheckModalForm.tsx, src/common/Modal/WarningModal/WarningMoalForm.tsx, src/components/Calendar/Calendar.tsx, src/components/Follower/Current/AdditionalProblemsModal.tsx, src/components/Follower/Current/NumOfQuestions.tsx, src/components/Follower/FollowerInfo.tsx, src/components/Follower/Personal/FollowerRecommendCard.tsx, src/components/Follower/Personal/ParticipatingGroup.tsx, src/libs/hooks/Admin/useDeleteMember.ts, src/types/CommonUserList/userListType.ts
=> [ Hotfix ] 빠르게 수정해야 하는 QA 내용 반영

src/components/MyProfile/FollowingList.tsx, src/components/MyProfile/MyGoal.tsx, src/components/MyProfile/Profile.tsx, src/components/MyProfile/ProfileEdit.tsx, src/components/Profile/GIthubInfo.tsx
=> [ Deploy ] Feat/profile -> develop merge 

src/common/CommonMonthSolve.tsx, src/components/Home/HomeHeader.tsx, src/components/Home/WeekFollowing/ProfileCard.tsx, src/components/Home/WeekFollowing/WeeklyFollower.tsx, src/components/Home/WeekRate.tsx
=> [ HotFix ] Home 뷰 빠르게 수정해야할 QA부분

src/assets/btn/btn_link_white.svg, src/assets/index.ts, src/common/CommonButton.tsx, src/components/GroupCreate/GroupSetting.tsx, src/components/GroupCreate/ImageSection.tsx, src/components/Home/WeekRate.tsx, src/constants/CommonBtn/BtnContent.tsx, src/page/GroupComplete.tsx, src/page/GroupCreate.tsx, src/types/GroupCreate/GroupCreateType.tsx
=> [ QA ] 그룹 뷰 QA 부분 빠르게 수정해야할 부분

src/common/CommonMonthSolve.tsx, src/components/Calendar/Calendar.tsx, src/components/Calendar/CustomCalendar.tsx, src/components/Home/HomeHeader.tsx, src/components/Home/TodaySolve.tsx
=> [ HotFix ] 홈 뷰 빠르게 수정해야할 부분 반영

src/common/CommonUserList.tsx, src/common/Modal/ErrorModal/ErrorModalForm.tsx, src/components/Admin/GroupStatistics/GroupStatistics.tsx, src/components/Follower/Personal/TotalSolutions.tsx, src/components/GroupDetail/GroupInfo.tsx, src/components/MyProfile/Profile.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx, src/components/Solve/Header/HeaderBottom.tsx, src/components/Solve/Header/PageHeader.tsx, src/libs/hooks/Follower/useGetUserProfile.ts, src/page/FollowerPage.tsx
=> [ Hotfix ] 에러 해결 및 ux 개선

src/common/CommonButton.tsx, src/common/CommonInput.tsx, src/common/CommonTextarea.tsx, src/common/RecommendCard.tsx, src/components/GroupAll/groupFilter/LanguageSelectBox.tsx, src/components/GroupCreate/GroupSetting.tsx, src/components/GroupCreate/ImageSection.tsx, src/components/GroupCreate/LanguageSection.tsx, src/components/MyGroup/ActiveGroups.tsx, src/components/MyProfile/FollowingList.tsx, src/components/MyProfile/MyGoal.tsx, src/components/MyProfile/Profile.tsx, src/components/Profile/NicknameInfo.tsx, src/components/Register/IntroInput.tsx, src/components/Register/NickName.tsx, src/components/Register/Select.tsx, src/page/GroupCreate.tsx, src/page/LoginPage.tsx, src/utils/handleInput.ts
=> [ Hotfix ] 빠르게 수정해야 하는 QA 내용 반영 

src/assets/icon/ic_graph_workbook.svg, src/assets/index.ts, src/common/CodeSpace/CodeEditor.tsx, src/common/CommonMonthSolve.tsx, src/common/Gnb.tsx, src/common/Header.tsx, src/components/Follower/Current/EmptyFollower.tsx, src/components/Follower/Personal/ParticipatingGroup.tsx, src/components/Home/HomeHeader.tsx, src/components/Home/TodaySolve.tsx, src/components/Home/WeekFollowing/ProfileCard.tsx, src/components/Home/WeekRate.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx, src/styles/style.d.ts, src/styles/theme.ts
=> [ 3차QA ] 빠르게 수정해야 하는 QA 내용 반영

src/page/GroupEdit.tsx
- close #238 
```
<ProfileButton>
<CancelButton type="button" onClick={handleCancelBtnClick}>
취소하기
</CancelButton>
<CommonButton
isActive={isActive}
category="Profile_save"
onClick={handleSaveBtnClick}
/>
</ProfileButton>
```
=> [ GroupEdit ] 그룹 수정하기 뷰 퍼블리싱

src/common/CommonUserList.tsx, src/common/RecommendCard.tsx, src/components/GroupAll/GroupItem.tsx, src/components/GroupMember/GroupInfo.tsx, src/components/MyGroup/PersonalGroup.tsx, src/components/Solve/Header/HeaderTop.tsx, src/components/Solve/Header/SolveToolTip.tsx, src/constants/Solve/SolveTooltipConst.tsx, src/libs/hooks/GroupJoin/usePostAnswer.ts, src/libs/hooks/Solution/useGetRecords.ts, src/libs/hooks/Solve/usePatchRecords.ts, src/page/GroupJoin.tsx, src/page/SolvePage.tsx, src/types/Solve/solveTooltipTypes.ts
=> [ Hotfix ] 모든 에러 해결 및 피그마와 다른 부분 수정

src/common/CommonUserList.tsx, src/common/RecommendCard.tsx, src/components/GroupMember/GroupInfo.tsx, src/components/MyGroup/PersonalGroup.tsx, src/components/Solve/Header/HeaderTop.tsx, src/components/Solve/Header/SolveToolTip.tsx, src/constants/Solve/SolveTooltipConst.tsx, src/libs/hooks/GroupJoin/usePostAnswer.ts, src/libs/hooks/Solution/useGetRecords.ts, src/libs/hooks/Solve/usePatchRecords.ts, src/page/GroupJoin.tsx, src/page/SolvePage.tsx, src/types/Solve/solveTooltipTypes.ts
=> [ Deploy ] Develop -> Main merge

src/common/CommonInput.tsx, src/components/GroupAll/GroupItem.tsx, src/components/GroupAll/GroupRecommend.tsx, src/components/GroupAll/groupFilter/LanguageSelectBox.tsx, src/components/GroupCreate/LanguageSection.tsx, src/components/GroupMember/GroupInfo.tsx, src/components/MyProfile/Profile.tsx, src/components/MyProfile/ProfileEdit.tsx, src/components/Profile/GIthubInfo.tsx, src/components/Profile/IntroInfo.tsx, src/components/Profile/LanguageInfo.tsx, src/components/Profile/NameInfo.tsx, src/components/Profile/RepositoriesInfo.tsx, src/components/Register/Repositories.tsx, src/constants/CommonInput/inputConst.ts, src/libs/apis/MyProfile/patchUser.ts, src/libs/apis/MyProfile/postCheckExitRepository.ts, src/libs/apis/Register/patchProfile.ts, src/libs/hooks/GroupEdit/useGetRoomsId.ts, src/libs/hooks/MyProfile/usePatchUser.ts, src/libs/hooks/MyProfile/usePostCheckExitRepository.ts, src/page/GroupEdit.tsx, src/page/RegisterPage.tsx, src/types/CommonInput/inputType.ts, src/types/GroupItem/groupItemType.ts, src/types/MyProfile/MyProfileType.tsx, src/types/Profile/ProfileType.tsx
=> [ Deploy ] develop -> main merge 

src/assets/icon/ic_new_alarm.svg, src/assets/index.ts, src/common/AlarmModal.tsx, src/common/Header.tsx, src/libs/apis/Alarm/getAlarmList.ts, src/libs/apis/Alarm/postAlarmRead.ts, src/libs/hooks/Alarm/useGetAlarmList.ts, src/libs/hooks/Alarm/usePostAlarmRead.ts, src/types/Alarm/alarmType.ts
=> [ deploy ] feat/Modal -> develop

src/common/AlarmModal.tsx, src/common/Header.tsx, yarn.lock
아름이가 이런 현상이 나타났다구 수정해달라고 요청사항이 왔어요 ! 
첫번째 알림을 눌렀을 때 정상적으로 URL 이 변경되면서 페이지가 이동이 되요. 하지만 그 화면에서 두번째 알림을 눌렀을 때 URL은 변경되지만 
화면이 정상적으로 그 화면으로 넘어가질 않은게 문제였어요.
아름이와 문주한테 문제점의 원인을 공유하면서 어떻게 해야할지 고민했습니다
처음에는 location 이 변경될 때 마다 location.pathname 을 줘야하나 고민했었어요.
알림을 클릭할 떄 다른 알림으로 이동하면 경로는 바뀌지만, 같은 컴포넌트가 재사용이 되면 화면이 리렌더링이 발생하지 않은 이유여서 사용을 했어요. 음 하지만 바뀐 데이터를 전달해줘야지만 페이지가 렌더링이 될 것 같아서 useEffect를 사용하지 않았어요.
**그래서 생각한게 클릭할 때 handle 함수에다가 추가적으로 navigate를 넣어보면 달라질까 ? 라는 생각이 들었어요 !** 
`navigate`함수는 특정 경로 이동 → 경로 변경 감지 → 컴포넌트나 페이지를 다시 렌더링 함.
Router는 location 객체를 사용하여 현재 경로를 관리. navigate 함수로 경로가 변경되면 location 상태가 업데이트 되며, 리렌더링이 발생하기 때문에 useEffect를 사용하지 않아두 된다구 하네요.
```tsx
// 변경전
const handleAlarmClick = (
notificationId: number,
type: string,
dataId: number
) => {
mutation({ notificationId, type, dataId }); …
```
=> [ Alarm ] 알림 클릭 후 페이지 URL은 변경되지만 화면이 렌더링이 되지 않는 현상 수정

src/common/AlarmModal.tsx, src/common/CommonMonthSolve.tsx, src/common/Header.tsx, src/common/SolutionList/SavedSolution.tsx, src/components/Follower/Current/Solver.tsx, src/components/Follower/Current/TodaysSolver.tsx, src/components/Follower/Personal/FollowerRecommendCard.tsx, src/components/Follower/Personal/Solutions.tsx, src/components/Home/HomeHeader.tsx, src/components/Home/TodaySolve.tsx, src/components/Home/WeekFollowing/ProfileCard.tsx, src/components/Home/WeekRate.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx, src/libs/hooks/Alarm/usePostAlarmRead.ts, src/page/FollowerCurrentPage.tsx, src/page/GroupComplete.tsx, src/styles/theme.ts, src/types/Follower/Current/currentType.ts
- close #issue_number
작업내용은 스크린샷으로 대체하겠습니다. 
```jsx
{newAlarms.map((data, idx) => {
const { notificationId, type, dataId } = data;
// /\[[^\]]+\]/g 정규식은 [ ]로 감싸진 텍스트를 [ ] 포함해서 추출
const bracketText = data.content.match(/\[[^\]]+\]/g);
//[ ]로 감싸진 부분을 기준으로 문자열을 분리합니다.
const nonBracketText = data.content.split(/\[[^\]]+\]/);
````
bracketText 와 nonBracketText 를 따로 분리하여 각각 스타일을 다르게 주었습니다.
음..bracketText 도 똑같이 split으로 나누려고 했습니다. 하지만 [ ] 로 감싸진 텍스트를 포함해서 추출하려면 [ ] 도 함께 포함해야 해서 split 보다는 match 가 적절하다고 생각했습니다.
밑에 이미지는  const bracketText = data.content.split(/\[[^\]]+\]/g); 으로 했을 떄 console.log 를 찍어본 것 입니다.
밑에 이미지는  const bracketText = data.content.match(/\[[^\]]+\]/g); 으로 했을 떄 console.log 를 찍어본 것 입니다.
근데 너무 코드가 지저분하고 해서 좋은 방법인건 아닌거 같아요,, 혹시 좋은 방법이 있을까요 ?
=> [ QA ] QA 3차 반영

src/common/Modal/SaveModalForm.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx, src/components/Solve/Header/SolveToolTip.tsx, src/page/SolutionPage.tsx
=> [ QA ] 3차 qa 반영

src/common/CommonButton.tsx, src/common/CommonUserList.tsx, src/components/Admin/GroupStatistics/GroupStatus.tsx, src/components/Admin/GroupStatistics/NumOfLanguages.tsx, src/components/Admin/GroupStatistics/NumOfMembers.tsx, src/components/GroupDetail/ApplicationModal.tsx, src/components/Solution/Header/SolutionHeaderTop.tsx
=> [ QA ] qa 반영 안된 부분 + 추가된 부분 반영

src/components/Landing/Landing10.tsx, src/components/Landing/Landing11.tsx, src/components/Landing/Landing2.tsx, src/components/Landing/Landing3.tsx, src/components/Landing/Landing4.tsx, src/components/Landing/Landing5.tsx, src/components/Landing/Landing6.tsx, src/components/Landing/Landing7.tsx, src/components/Landing/Landing8.tsx, src/components/Landing/Landing9.tsx, src/page/LandingPage.tsx
=> [ Landing ] 랜딩페이지 전체적으로 스타일 수정

src/components/Calendar/Calendar.tsx
=> [ Hotfix ] 캘린더 부분 변경사항 수정

src/common/SolutionList/SavedSolutionList.tsx, src/page/GroupDetail.tsx
=> [ deploy ] develop -> main 캘린더 수정 사항 merge

src/components/Calendar/Calendar.tsx
- close #issue_number
Hotfix 브랜치 참고 부탁드립니다.
=> [deploy] develop -> main merge

src/common/Modal/SaveModalForm.tsx, src/components/Landing/Landing4.tsx
- close #326 
둘 다 라이팅 변경하는 이슈였기 때문에, 큰 변경사항은 없습니다 ~
=> [ Refactor ] 라이팅 수정

src/common/CodeSpace/Memo.tsx, src/components/Solve/Header/HeaderBottom.tsx, src/components/Solve/Header/HeaderTop.tsx, src/page/SolvePage.tsx
- close #331 
제목에 적어둔 것처럼 사용성 개선을 위해 커서에 Pointer를 적용했어요. 또한, 버튼의 역할을 하고 있지만 div로 구현되어 있던 부분에 시멘틱 태그를 적용하여 button 태그로 수정했어요.
클릭이벤트가 적용되지만 커서가 pointer가 아닌 경우 사용자가 클릭이벤트가 없다고 오해할 확률이 높다고 생각했어요.
특히 문제풀이 등록 > 플랫폼/ 문제유형 선택부분은 Input으로 구현되어 있어, 호버했을 때 입력창에 들어가는 커서가 떠서 더 어색하게 느껴지더라구요.
그래서 이 부분들 모두 `cursor: pointer;`나 `button 태그`를 활용하여 클릭하는 요소임을 알려주도록 수정했습니다.
=> [ Refactor ] 사용성 개선을 위해 cursor: pointer; 적용

src/common/Header.tsx, src/components/Calendar/Calendar.tsx
=> [ deploy ] develop -> main 

src/components/GroupCreate/ImageSection.tsx, src/components/Home/TodaySolve.tsx, src/components/Home/WeekRate.tsx, src/components/MyProfile/ProfileEdit.tsx, src/components/Profile/GIthubInfo.tsx, src/components/Profile/IntroInfo.tsx, src/components/Profile/LanguageInfo.tsx, src/components/Profile/NicknameInfo.tsx, src/components/Profile/RepositoriesInfo.tsx, src/components/Register/NickName.tsx, src/components/Register/Repositories.tsx, src/page/RegisterPage.tsx
- close #344 
https://github.com/user-attachments/assets/d380c997-f0dd-4d42-9d2d-dbe64c1eda48
닉네임 버튼과 리포지토리 버튼 각각 유효성 검사를 추가했습니다.
```
const isButtonEnabled = nickname.length > 0 && nickname.length <= 10; // 닉네임 버튼
const isButtonEnabled = repositories.length > 0; // 리포지토리 버튼
```
- x 아이콘 추가 및 바뀐 디자인 반영 했습니다.
수정된 디자인 토대로 툴팁 적용하고 수정된 라이팅 부분 적용했습니다.
=> [ Hotfix ] 툴팁 추가 + 내 프로필 수정 뷰 스타일 수정
