Co-Drive/Driver-Client

- src/common/CommonInput.tsx
- src/common/InputText.tsx
- src/constants/CommonInput/inputConst.ts
- src/styles/globalStyle.ts
- src/styles/style.d.ts
- src/styles/theme.ts
- src/types/CommonInput/inputType.ts
- close #2 
<br />
https://github.com/user-attachments/assets/53f29db4-11e4-42ca-bb6b-7597944d2791
<br />
- input의 역할에 맞춰 카테고리 분리해두었습니다.
- title, num, nickname, github, password, secretKey
- 조건부 스타일링을 통해 카테고리 별로 placeholder, 너비, 배경색, 폰트, 마진 값이 다르게 들어가도록 구현했습니다.
- 조건부 렌더링을 통해 카테고리 별로 다르게 렌더링 될 부분 구현했습니다.
- 아이콘 들어갈 부분은 주석으로 표시해뒀고, 추후 아이콘 내용 업데이트 되면 넣을 예정입니다!
<br />
1. input에 들어갈 내용을 업데이트하고 저장하기 위해서 보통 **useState**를 사용하잖아요! 
요걸 **구조분해할당**을 활용한 아래 형태로 정의해주세요! 
(카테고리 전부 정의하실 필요 없고, 각자 상황에 필요한 카테고리만 정의해주시면 됩니당 !! title, num input만 필요한 경우 두 개의 필드만 정의하시면 돼요 !)
```typescript
const [inputs, setInputs] = useState({
title: '',
num: '',
secretKey: '',
password: '',
nickname: '',
github: '',
});
```
<br />
2. 위에서 정의한 객체를 **한 번 더 구조분해할당** 해서 사용하기 편리한 형태로 만들어주세요 !
```typescript
const { title, num, …
```
> [ Common ] 공통 input 컴포넌트 만들기

- src/common/Header.tsx
- src/components/PageLayout/PageLayout.tsx
- close #46 
- `align-items: center` 추가
- 피그마 상의 뷰들 모두 가로 중앙 정렬이라 요거 추가했습니당
- 특히 얘를 적용했을 때 컴포넌트 설계가 달라지는 것들이 있을 거라서 hotfix로 브랜치 팠습니당
- 닉네임 들어가는 영역을 피그마와 동일하게 잡고, 오른쪽 정렬했습니당
> [ Hotfix ] 헤더, 페이지 레이아웃 수정

- src/assets/icon/ic_link_purple.svg
- src/assets/index.ts
- src/common/CodeSpace/CodeEditor.tsx
- src/common/CodeSpace/Memo.tsx
- src/components/Solution/Header/SolutionHeaderBottom.tsx
- src/components/Solution/Header/SolutionHeaderTop.tsx
- src/components/Solve/CodeSpace.tsx
- src/page/SolutionPage.tsx
- src/types/Solve/solveTypes.ts
- close #12 
https://github.com/user-attachments/assets/cf092c04-192c-427a-a061-2024409cb314
- 원래는 feat/solution 브랜치를 하나 파려구 했는데 feat/solve 브랜치에서 작업한 컴포넌트들을 활용하기 위해서 feat/solve 브랜치에서 분기했습니당
- feat/solve에서 작업한 내용의 코드리뷰가 아직 마무리되지 않아서 상위 브랜치로 따로 머지하지 않고 feat/solve 브랜치 그대로 사용했습니다!
<br />
- 코드 에디터/ 메모 컴포넌트는 원래 문제 풀이 등록 뷰에서 정의/ 사용하던 컴포넌트였는데, 이번 뷰를 구현하려고 보니까 코드/ 메모 부분이 동일하게 들어가더라구요!
- 그래서 공통 컴포넌트로 변경해서 Solution 컴포넌트에서도 사용했습니다 !
<br />
- Solution에서는 해당 컴포넌트들을 readOnly로 띄워줘야 했어요 !
- isReadOnly라는 props를 추가해서 읽기 모드/ 편집 모드로 나뉘도록 분기처리했습니다.
- 이때 onChange 함수는 편집 모드에서만 유효한 함수이기 때문에, nullable로 타입을 변경하고 !isReadOnly이고 핸들링 함수를 props로
전달받았을 경우에만 동작하도록 구현했습니다.
```typescript
<CodeMirror
onChange={(newCode) => {
if (!isReadOnly && handleChangeCode)
handleChangeCode({ newCode, stringId });
}}
...
/>
``` …
> [ Solve/ Solution ] 풀었던 문제 다시보기(본인) 뷰 퍼블리싱

- src/assets/icon/ic_arrow__top_white.svg
- src/assets/icon/ic_arrow_bottom_white.svg
- src/assets/icon/ic_calendar.svg
- src/assets/index.ts
- src/components/Solution/Level.tsx
- src/components/Solution/List/Calendar.tsx
- src/components/Solution/List/ListFilter.tsx
- src/components/Solution/List/SavedSolution.tsx
- src/components/Solution/List/SavedSolutionList.tsx
- src/components/Solution/List/TempSave.tsx
- src/page/SolutionListPage.tsx
- src/types/Solution/solutionTypes.ts
- close #94 
https://github.com/user-attachments/assets/5095c7c9-9fde-4f0d-9bd4-819c93fa2d9b
- 12개의 숫자가 들어가 있는 년도 별 캘린더를 구현했습니다.
- 문제 풀이가 진행되지 않은 달의 정보를 받아와서 문제 풀이 진행 여부에 따라 조건부 스타일링 적용했습니다!
- 현재는 문제 풀이가 진행되지 않은 달의 정보를 더미데이터로 넣어놨고, 스웨거에 해당 api 가 없어서 서버 측에 요청해둔 상태입니당
```typescript
const dummy = [1, 3, 5, 10];
<MonthBoard>
{monthCalendar.map((month) => {
const disabled = dummy.includes(month) || clickedYear > year;
return (
<Month
key={month}
$disabled={disabled}
$isClicked={clickedMonth === month}
onClick={() => !disabled && handleClickMonth(month)}
>
{month}
</Month>
);
})}
</MonthBoard>
```
<br />
- 페이지 별로 서버에 데이터를 요청할 예정이라 현재는 페이지네이션 틀만 잡아뒀습니당
- 특이사항은 없고, 클릭된 페이지에 조건부 스타일링 걸고 화살표 아이콘에 각각 핸들링 함수 걸어뒀습니다.
> [ Solution ] 풀었던 문제 리스트 컴포넌트 퍼블리싱

- src/assets/icon/thumbnail.svg
- src/assets/index.ts
- src/components/GroupCreate/CreateButton.tsx
- src/page/GroupComplete.tsx
- src/page/GroupCreate.tsx
- src/types/GroupCreate/GroupCreateType.tsx
- close #104 
https://github.com/user-attachments/assets/a606c5a3-f35e-491d-ad4c-04b0b2a81d8e
https://github.com/user-attachments/assets/28b8cfd1-5844-4db8-81de-bc5ad644ba80
GroupComplete 페이지에서 state 값으로 useLocation 을 받고있다.
useLocation 훅을 사용하면 현재 위치에 대한 정보를 가져올 수 있다. 이 훅을 사용하여 navigate를 통해 다른 페이지로 이동할 때 전달한 상태를 가져올 수 있는데 우리는 `groupPassword` 와 `thumbnailUrl` 이 두개가 state로 필요했던 것.
현재 이 페이지는 그룹생성 후→ 그룹 참여가 완료되었다는 페이지이다.
```jsx
const GroupComplete = () => {
const navigate = useNavigate();
const { state } = useLocation();
const { groupPassword, thumbnailUrl } = state;
return (
<PageLayout category={'group_create'}>
<Title>그룹 생성이 완료되었어요!</Title>
<PasswordContainer>
<PasswordText>
비밀번호 <Password>{groupPassword}</Password>
</PasswordText>
</PasswordContainer>
<ThumbnailContainer>
<Img …
```
> [ Group ] GroupComplete Navigate 연결

- src/components/Solution/List/Calendar.tsx
- src/components/Solution/List/ListFilter.tsx
- src/components/Solution/List/SavedSolutionList.tsx
- src/libs/apis/Solution/getMonthlySolution.ts
- src/libs/apis/Solution/getUnsolvedMonths.ts
- src/types/Solution/solutionTypes.ts
- close #111 
https://github.com/user-attachments/assets/4c77d05a-5ff1-41b8-9646-1a0c43e81e9b
- 값 변경에 따른 리렌더링을 방지하기 위해 [🔗 useRef](https://ko.react.dev/reference/react/useRef) 를 활용했습니다.
- 년도가 바뀌면 문제풀이 없는 달을 다시 가져와야 하기 때문에 useEffect dependency로 year 값을 넣어줬어요
```typescript
const getUnsolvedMonthsArr = async () => {
try {
const { data } = await getUnsolvedMonths(year);
const { months } = data;
unsolvedMonths.current = months;
} catch (err) {
console.log(err);
}
};
useEffect(() => {
getUnsolvedMonthsArr();
}, [year]);
```
<br />
- 선택된 달에 저장된 문제풀이 정보를 가져오는 api를 연결해서 안에 저장된 데이터로 각각 전체 페이지, 기록 state 값을 업데이트 했어요.
- 아래 함수 내부에 있는 updateTotalPage(), updateRecords() 함수는 TempSave.tsx와 거의 동일하게 구현했습니다 ! 
(#110 참고)
```typescript
const getMonthlySolutionList = async () => {
const { data } = await …
```
> [ Solution ] 문제풀이 다시보기 리스트 컴포넌트 구현

- src/Router.tsx
- src/common/Groups.tsx
- src/common/RecommendCard.tsx
- src/components/MyGroup/ActiveGroup.tsx
- src/components/MyGroup/ActiveGroups.tsx
- src/components/MyGroup/RecommendGroup.tsx
- src/constants/MyGroup/myGroupConts.ts
- src/page/GroupAllPage.tsx
- src/page/MyGroup.tsx
- src/types/GroupAll/RecommendCardType.ts
- src/types/MyGroup/myGroupType.ts
- close #13 
https://github.com/user-attachments/assets/90cd4da2-1e37-4932-af2f-558d78fea3b5
- 변경된 홈 뷰에서는 요 공통 컴포넌트가 사용되지 않는줄 알았는데 홈에서도 사용이되길래 함께 사용할 수 있도록 isLongPage라는 props를 추가해서 해당 컴포넌트가 2*3, 3*3 레이아웃을 유지하도록 했어요.
- users라는 props는 전달만 될 뿐, 다른 컴포넌트에서 사용되지 않길래 props에서 제거해줬습니당
<br />
- 내 그룹 뷰에서 쓰이는 페이지네이션이 적용된 그룹 리스트 컴포넌트가 홈 뷰에서도 쓰이더라구요!
- 함께 사용할 수 있도록 공통 컴포넌트로 만들어줬습니당 ~
<br />
- 기존에 문주언니가 만들어준 컴포넌트를 그대로 가져와서 사용하려고 했는데, 디자인 상 조금 다른 부분도 있고 슬라이드 부분 로직이 잘 이해가 가지 않아서 조금 더 간단한 로직으로 구현해보았습니다 !
- 대신 언니가 기존에 만들어줬던 슬라이더 애니메이션을 그대로 사용하고 싶었는데 제가 변경한 코드에 적용하니까 잘 안되더라구요 ㅠ_ㅠ 조만간 다시 만져보겠습니다 !!
> [ MyGroup ] 내 그룹 뷰 퍼블리싱

- src/Router.tsx
- src/common/CommonButton.tsx
- src/components/GroupCreate/GroupSetting.tsx
- src/components/GroupCreate/LanguageSection.tsx
- src/constants/GroupCreate/LanguageConst.tsx
- src/libs/apis/GroupComplete/getGroupInfo.ts
- src/libs/apis/GroupCreate/postGroupInfo.ts
- src/page/GroupComplete.tsx
- src/page/GroupCreate.tsx
- src/types/GroupCreate/GroupCreateType.tsx
- close #132 
https://github.com/user-attachments/assets/1ff81484-13cf-4fa5-947d-76d0b164969f
All 선택 시 'ALL' 이라는 string 도 함께 들어가서 서버로 전송이 되지 않았던 것이였어요 !
```const [isAllSelected, setIsAllSelected] = useState(false);```
때문에 all 을 선택을 한지 안한지 구분하려는 state를 하나 추가하여 만들어 주었습니다. 사실 이게 맞는건지도 아직 잘 모르겠긴 하는데,, PR로 남겨주시면 감사하겠습니다
selectAllTag 라는 함수를 하나 생성하여 현재 담겨있는 태그에 모든 언어들을 넣어주고 드롭다운을 시킵니다.
```jsx
const selectAllTags = () => {
setIsAllSelected(true);
setSelectedTags(DUMMY);
toggleDropdown();
};
```
그 다음 isAllSelected 가 true 이면 ALLTAG 가 담겨있는 태그가 UI로 나오게 되면서 변경해주었습니다.
```jsx
{isAllSelected ? (
<SelectedTagContainer key={ALL_TAG}>
<CommonHashTag
selectedTag={ALL_TAG}
removeTag={() => removeTag(ALL_TAG)}
/>
</SelectedTagContainer>
) 
```
서버에 전달되는 값 중 'ALL'이라는 string이 들어간지도 모르고 계속 해메고 있었네요,,
커밋이 좀 많아졌는데 …
> [ Group ] All 태그 선택 시 서버에 전달 안되는 현상

- src/assets/icon/ic_nothing.svg
- src/assets/icon/ic_workbook_black.svg
- src/assets/index.ts
- src/components/Follower/Current/CustomTooltip.tsx
- src/components/Follower/Current/EmptyFollower.tsx
- src/components/Follower/Current/EmptySolver.tsx
- src/components/Follower/Current/FollowerCurrentGraph.tsx
- src/components/Follower/Current/FollowerList.tsx
- src/components/Follower/Current/FollowerQuestions.tsx
- src/components/Follower/Current/NumOfQuestions.tsx
- src/components/Follower/Current/Solver.tsx
- src/components/Follower/Current/TodaysSolver.tsx
- src/components/Follower/Current/WeeklyCurrentGraph.tsx
- src/constants/Follower/currentConst.ts
- src/page/FollowerCurrentPage.tsx
- src/types/Follower/Current/currentType.ts
- close #141 
<br />
- 원래는 그래프 호버로 툴팁이 뜨는데 모바일 뷰로 작게 띄워놓고 보느라 그래프 클릭해서 영상 찍었습니당
https://github.com/user-attachments/assets/1910834d-9d61-45b9-ad8d-13ea24cf4b39
- 팔로워 수가 15명 이하인 경우, 빈 막대 그래프를 세워야 해서 이 때는 유저 정보를 채운 뒤, 15번째 인덱스까지 `{ name: '', problemNum: 0, height: 50 }`로 채워진 배열을 만들어서 사용했습니다.
```typescript
// 원래 팔로워 데이터
const data = users.map((user) => {
const { nickname, problemNum } = user;
const height = problemNum * 10 + 10;
return {
name: nickname,
problemNum: problemNum,
height: height,
};
});
// 가공한 팔로워 데이터
const filledData = Array(15)
.fill(0)
.map((_, index) => {
return data[index] || { name: '', problemNum: 0, height: 50 };
});
// 팔로워 수에 따라 그래프 구현에 사용할 배열 선택
const barArr = data.length >= 15 ? data : filledData;
```
<br />
- `getColor` 라는 함수를 만들어서 문제 수에 맞는 색상을 렌더링했습니다.
- 그런데 문제 수가 …
> [ Follower ] 팔로워 현황 상단 뷰 구현

- src/components/Follower/Current/CustomTooltip.tsx
- src/components/Follower/Current/FollowerCurrentGraph.tsx
- src/components/Follower/FollowerInfo.tsx
- src/components/Follower/Personal/FollowerRecommendCard.tsx
- src/libs/apis/Follower/deleteFollower.ts
- src/libs/apis/Follower/postFollower.ts
- src/libs/apis/Follower/updateFollower.ts
- src/libs/hooks/Follower/useGetFollowerSummary.ts
- src/libs/hooks/Follower/useUpdateFollower.ts
- src/types/Follower/Personal/personalType.ts
- close #97 
https://github.com/user-attachments/assets/fa6541ff-342e-4c00-a196-35ea1454739e
- 두 api가 post/ delete인 것만 빼면 모두 동일한 구조를 가져서 공통 함수로 구현했어요
- 팔로우/ 언팔로우가 진행될 때는 무조건 현재 팔로우 여부 데이터를 가지고 있기 때문에, 팔로우 여부 값을 props로 받아서 현재 팔로우 중이라면 delete 함수를 호출하고 언팔로우 중이라면 post 함수를 호출했습니다.
```typescript
const updateFollower = async ({ isDelete, nickname }: UpdateFollowerProps) => {
const { data } = isDelete
? await api.delete(`/follow/${nickname}`)
: await api.post(`/follow/${nickname}`);
return data;
};
```
<br />
- queryClient에 invalidateQueries를 하면 쿼리 키에 해당하는 데이터가 변했다면 최신 데이터로 패칭시켜주는데요,
쿼리 키를 여러 개 지정한다면 원래 키를 지정하는 방식대로 하나의 배열 안에 키를 넣어주면 된다고 생각했어요 !
```typscript
queryClient.invalidateQueries({ queryKey: ['get-follower-summary', 'get-user-profile', ...] });
```
- 그런데 예상과는 달리 이렇게 하니까 데이터 패칭이 잘 이뤄지지 …
> [ Follower ] 팔로우/ 언팔로우 api 연결

- src/common/CommonMonthSolve.tsx
- src/components/Calendar/Calendar.tsx
- src/components/Home/TodaySolve.tsx
- src/components/Home/WeekFollowing/ProfileCard.tsx
- src/components/Home/WeekFollowing/WeeklyFollower.tsx
- src/components/Home/WeekRate.tsx
- src/libs/apis/Home/getFollowingsCheck.ts
- src/libs/apis/Home/getMonthSolve.ts
- src/libs/apis/Home/getUserAchieve.ts
- src/libs/apis/Solution/getMonthlySolution.ts
- src/libs/hooks/Home/useGetFollowingsCheck.ts
- src/libs/hooks/Home/useGetMonthSolve.ts
- src/libs/hooks/Home/useGetUserAchieve.ts
- src/types/Home/calendarType.ts
- src/types/Home/getMonthSolveTypes.ts
- src/types/Home/todaySolveType.ts
- src/types/Week/HomeFollowerTypes.ts
- close #170 
파라미터로 userID 값과 pivotDate 가 들어갑니다. userID 는 세션에서 가져오면서 해결하고, pivotDate 는 쿼리 파라미터를 이용하여 전달을 해주었습니다.
```jsx
const getMonthSolve = async ({ year, month }: getMonthSolveProps) => {
const userId = sessionStorage.getItem('user');
const formatMonth = month < 10 ? `0${month}` : `${month}`;
const { data } = await api.get(
`/records/${userId}/board?pivotDate=${year}-${formatMonth}-01`
);
```
또한 totalCount, longestPeriod, maxCount 값이 바뀔떄마다 리렌더링이 되어야 하기 때문에 useEffect를 사용하였습니다.
```jsx
const { data } = useGetMonthSolve({
year: clickedYear,
month: clickedMonth,
});
useEffect(() => {
if (data) {
const { totalCount, longestPeriod, maxCount } = data.data;
setStats({
totalCount,
longestPeriod,
maxCount,
});
}
}, [data]);
```
파라미터 값으로 아무것도 받지 않음으로 스웨거에 있는 그대로 작성하였습니다. 
```jsx
const …
```
> [ Home ] Home API 부분 연결 

- src/Router.tsx
- src/common/CommonInput.tsx
- src/common/Header.tsx
- src/components/MyProfile/FollowingList.tsx
- src/components/MyProfile/MyGoal.tsx
- src/components/MyProfile/Profile.tsx
- src/components/MyProfile/ProfileEdit.tsx
- src/components/Profile/NicknameInfo.tsx
- src/libs/apis/MyProfile/deleteUser.ts
- src/libs/apis/MyProfile/getFollowList.ts
- src/libs/apis/MyProfile/getUser.ts
- src/libs/apis/MyProfile/patchGoal.ts
- src/libs/apis/MyProfile/patchUser.ts
- src/libs/apis/MyProfile/postCheckExitNickname.ts
- src/libs/hooks/Follower/useUpdateFollower.ts
- src/libs/hooks/MyProfile/useDeleteUser.ts
- src/libs/hooks/MyProfile/useGetFollowList.ts
- src/libs/hooks/MyProfile/useGetUser.ts
- src/libs/hooks/MyProfile/usePatchGoal.ts
- src/libs/hooks/MyProfile/usePatchUser.ts
- src/libs/hooks/MyProfile/usePostCheckExitNickname.ts
- src/types/CommonInput/inputType.ts
- src/types/MyProfile/MyProfileType.tsx
- src/types/Profile/ProfileType.tsx
- close #186 
https://github.com/user-attachments/assets/78fdb201-ca56-47ac-ae4a-2338f5a1241c
<br />
- 위에 체크해둔 api 연결했습니다.
- 내 프로필 뷰로 넘어오려면 헤더에 있는 프로필을 클릭하면 됩니다.
- 기존 조건대로라면 닉네임을 변경 후 중복검사를 하지 않아도 잘 저장이 되고, 옵션으로 설정된 한 줄 소개나 깃허브 링크가 저장되지 않는다면 에러를 뱉는 등 여러 문제가 있었어요.
이걸 해결하기 위해서 조건들을 변경해줬고, 지금도 완벽하진 않지만 이전보단 올바른 로직으로 동작하고 있습니다. 
(이 부분은 담당자인 문주언니가 더 보충해주면 좋을 것 같아요)
```typescript
const isActive =
((originNickname !== nickname &&
isClickedCheckBtn &&
!isExitNickname &&
nickname.length > 0 &&
nickname.length <= 10) ||
originNickname === nickname) &&
((language !== selectedLanguage && selectedLanguage.length > 0) ||
language === selectedLanguage) &&
(!comment || (comment.length > 0 && comment.length <= 30)) &&
(!githubUrl || githubUrl.length > 0);
```
<br />
- e.stopPropagation이 원인임을 파악
- 그러나 여러 …
> [ Profile ] api 연결

- src/common/CommonMonthSolve.tsx
- src/components/Follower/FollowerInfo.tsx
- src/components/Follower/Personal/Graph/CustomLabel.tsx
- src/components/Follower/Personal/Graph/SuccessRate.tsx
- src/libs/apis/Home/getMonthSolve.ts
- src/libs/hooks/Home/useGetMonthSolve.ts
- src/page/FollowerPage.tsx
- src/page/Home.tsx
- src/page/SolvePage.tsx
- src/types/Home/getMonthSolveTypes.ts
- src/utils/handleClickGoTopBtn.ts
- close #146 
https://github.com/user-attachments/assets/acd0df49-5696-4d82-9fdc-cf44aa2f7863
- 파이 그래프 두개 + label로 이미지 넣기 형태로 구현했습니다.
- 기존 승택오빠나 제가 했던 방식과 동일합니다 !
<br />
- 이 아이콘이 문제풀이 등록하기 뷰에도 사용되어서 두 군데 모두에서 개발했습니다
- 페이지 상단에 도착하면 더이상 해당 아이콘이 있는 의미가 없기때문에 투명도 0으로 변하게 구현했습니다.
> [ Follower ] 개인뷰 그래프 구현

- src/components/GroupAll/GroupItem.tsx
- src/types/GroupItem/groupItemType.ts
All 태그 눌렀을 시 서버로 전송이 안된다는 말을 듣고, console.log를 찍어봤는데 데이터는 잘 들어오고 있었습니다. 
하지만 문제는 All 태그 그룹이 화면에 렌더링이 되지 않는것이 문제점이였습니다.
```const [searchResults, setSearchResults] = useState([]); ``` 이 코드는 검색창에 그룹을 찾아주는 state 였는데, 
배열로 들어가 있어서 콘솔을 찍어보니 그룹 전체값을 렌더링 해주고 있었습니다. 그래서 ALL 태그를 눌렀을 떄 값을 확인해보니,
사진과 같이 빈값이 들어가는걸 확인할 수 있었습니다. 
❗️ 그렇다면 필터링 처리 해주는 함수에서 수정을 한번 해보자 라는 생각이 들었습니다.
**수정전 코드**
```jsx
const filterGroups = (groups: any[]) => {
return groups.filter((group) => {
const isAllTagSelected = selectedTags.includes(ALL_TAG);
const groupHasAllTag = group.tags.includes(ALL_TAG);
const tagMatch =
selectedTags.length === 0 ||
(isAllTagSelected && groupHasAllTag) ||
selectedTags.every((tag) => group.tags.includes(tag)); // 인코딩되지 않은 상태로 비교
const sliderMatch =
group.memberCount >= sliderValues.min && …
```
> [ GroupAll ] All 태그 눌렀을 시 그룹 렌더링 안되는 부분 수정

- src/assets/icon/ic_new_alarm.svg
- src/assets/index.ts
- src/common/AlarmModal.tsx
- src/common/Header.tsx
- src/libs/apis/Alarm/getAlarmList.ts
- src/libs/apis/Alarm/postAlarmRead.ts
- src/libs/hooks/Alarm/useGetAlarmList.ts
- src/libs/hooks/Alarm/usePostAlarmRead.ts
- src/types/Alarm/alarmType.ts
- close #260 
```jsx
// Header.tsx
const { data, isLoading } = useGetAlarmList();
const { notifications } = !isLoading && data?.data;
};
```
notifications 안에 있는 데이터들을 AlarmModal 컴포넌트로 데이터를 내려주었습니다.
알림 스트림 등록과 해제가 있긴 하였지만 , 읽음 목록 조회를 테스트 해보기 위해서 새로운 알림과 알림 읽음 목록을 분기처리 하였습니다.
filter 처리를 해주어서 isRead 가 false 면 새로운 알림, true 이면 읽음 알림으로 처리해주었습니다.
렌더링될 때 서버에서 undefiend가 잠깐 처리되고 그 후 데이터를 가져오는 형식이여서 data가 로드되지 않았을 때 배열을 빈 배열로 처리해주어 오류를 막아주었습니다.
```jsx
// notifications가 로드되지 않았을 때 빈 배열을 기본값으로 설정
// AlarmModal.tsx
const newAlarms =
notifications?.filter((data) => data?.isRead === false) || [];
const readAlarms =
notifications?.filter((data) => data?.isRead === true) || [];
const { mutation } = usePostAlarmRead();
```
여기서 제일 애먹었던것 같습니다.. 사실 onSuccess 를 useQuery 안에서 처리해주고 싶었는데 조금 급하게 하다보니 어떻게 해야할지 몰라서 …
> [ Alarm ] API 연결

- src/common/Header.tsx
https://github.com/user-attachments/assets/26f52f1d-4cde-457b-b5f9-82763c539723
- 새로운 알림 여부에 따라 state 값이 변하도록 구현해놨는데, 이때 새로운 알림 유/무를 판단하는 조건이 잘못되어서 발생한 문제였어요.
- 이걸 해결하기 위해서 state의 초기 값을 `newAlarms.length > 0`로 설정하여 해당 조건을 만족한 경우 true, 그렇지 않은 경우 false 값을 갖도록 정의했어요.
이후 새로운 알림이 들어올 때마다 동작하는 useEffect 문 내부에도 newAlarms.length > 0인 경우 state 값을 true, 그렇지 않은 경우 false를 할당하여, 새로운 알림 유/무에 따라 프로필 사진에 초록색 동그라미가 제대로 뜨도록 구현했습니다.
> [ Hotfix ] 새로운 알림이 없음에도 프로필 사진에 초록색 동그라미 없어지지 않는 이슈 해결

- src/common/AlarmModal.tsx
- src/components/Follower/Personal/FollowerRecommendCard.tsx
- src/components/GroupDetail/ApplicationModal.tsx
- src/libs/hooks/Admin/useGetParticipantsList.ts
- src/libs/hooks/Admin/useGetRoomInfo.ts
- src/libs/hooks/Alarm/usePostAlarmRead.ts
- src/libs/hooks/Follower/useGetUserProfile.ts
- src/libs/hooks/GroupDetail/useGetDetail.ts
- src/libs/hooks/GroupMember/useGetMemberList.ts
- src/libs/hooks/GroupMember/useGetRanking.ts
- src/page/FollowerCurrentPage.tsx
- src/utils/updateWeek.ts
- close #285 
- 기존에는 승인받은 사람 수에 그룹장도 포함이 되어있어서, 서버에서 `받아온 승인받은 사람 수 - 1`의 값을 띄워주고 있었어요.
- 이제는 승인받은 사람 수에 그룹장이 포함되어있지 않은 값이 들어오고 있어서 기존 코드대로 하니까 실제와 다른 숫자를 띄워주게 되더라구요!
그래서 이 부분은 서버에서 받아온 값 그대로를 띄워주는 방식으로 수정했어요. (스크린샷 첨부)
<br />
- 기존에 정의된 코드에서는 정상적인 url로 접근하기 전 잘못된 주소를 거치기 때문에, 새로운 알림을 클릭했을 때 화면 깜빡임과 뒤로가기를 실행했을 때 잘못된 주소로 접근했다는 에러가 발생했어요.
- 화면 깜빡임 발생 이유: 잘못된 주소로 접근 -> 빈 화면 띄워줌 -> 정상적인 주소로 라우팅 -> 실제 데이터 띄워줌 -> 이 과정에서 깜빡임이 있는 것`처럼` 느껴짐 
(사실은 잘못된 주소를 거쳐가는 과정)
- 뒤로 가기 실행 시 잘못된 주소로 접근했다는 에러 발생 이유: 정상적인 주소 -> 뒤로가기 -> 잘못된 주소로 접근하기 때문 
(위에서 이야기한 것러럼, 정상적인 주소로 접근하기 위해 반드시 잘못된 주소를 거쳐가기 때문에 뒤로가기를 실행했을 때는 이전 루트인 잘못된 주소로 갈 수 밖에 없음)
- **해결 방법**
- 앞서 정의된 잘못된 주소로 향하는 navigate 코드를 모두 삭제
- 그룹/ 팔로워 id가 변경되었을 때 최신 데이터를 불러오도록 하기 위해 react-query querykey에 그룹/ 팔로워 id 추가
- 그룹/ 팔로워 id가 변경되었을 때 최신 데이터를 불러옴 
<br />
- …
> [ Hotfix ] 기존 로직과 다르게 동작하는 부분 수정

- src/common/CommonUserList.tsx
- src/common/SolutionList/ListFilter.tsx
- src/common/SolutionList/SavedSolutionList.tsx
- src/components/Calendar/Calendar.tsx
- src/libs/apis/Solution/getMonthlySolution.ts
- src/libs/apis/Solution/getUnsolvedMonths.ts
- src/libs/hooks/Solution/useGetMonthlySolution.ts
- src/libs/hooks/Solution/useGetUnsolvedMonths.ts
- src/types/Solution/solutionTypes.ts
- close #288 
https://github.com/user-attachments/assets/494d0d84-0249-4ef0-8d49-1628e5a17c56
1. 팔로잉 수와 관계없이, 추천 카드가 보이도록 수정
- 기존에 있었던 `users.length === 0`이라는 조건을 삭제하여 팔로워 수와 관계없이 모든 팔로워 뷰에 추천 컴포넌트가 뜨도록 구현했어요.
2. 팔로워 개인 페이지에서 문제풀이를 보여주는 경우, 최근 푼 5문제를 보여주도록 수정
- 기존에는 현재 속한 달의 최근 푼 5문제를 보여줬는데, 디자이너 측 요청에 따라 팔로워가 푼 전체 문제 중 5문제를 보여주도록 수정했어요.
<br />
- 기존 페이지네이션 관련 로직이 꼬여있음을 알게 되어서 복잡한 로직을 간단하게 풀었어요.
- 페이지네이션 초기 값을 1로 수정하여 문제풀이가 없는 경우에도 현재 페이지에 1이라는 숫자가 떠있도록 수정했어요.
<br />
- 현재 접근한 팔로워 뷰의 유저가 푼 문제와 관계없이 일정하게 9, 10월만 활성화되어 있는 것을 알게 되었어요.
- 코드를 뜯어보니 문제풀이를 하지 않은 달을 불러오는 api에서 userId를 현재 접속한 유저의 id(본인의 userId)로 제한하고 있어, 팔로워 뷰에 접근하더라도 본인의 문제풀이 현황이 반영되고 있었어요.
- 이를 해결하기 위해서 팔로워 뷰에서 접근한 경우, followerId라는 nullable한 Props를 내려주어 해당 id에 맞는 정보를 가져오되 본인의 문제풀이 정보를 가져오는 로직에는 영향이 가지 않도록 수정했어요.
<br />
- 단체 방에서도 …
> [ Hotfix ] 변경된 로직 반영 + 새롭게 발견한 이슈 수정

- src/Router.tsx
- src/common/Header.tsx
- src/components/Landing/Landing1.tsx
- src/components/Landing/Landing11.tsx
- src/components/Landing/Landing4.tsx
- src/components/PageLayout/PageLayout.tsx
- src/libs/hooks/SSE/useDeleteNotification.ts
- src/page/Home.tsx
- src/page/LandingPage.tsx
- src/page/LoginPage.tsx
- close #293 
https://github.com/user-attachments/assets/f3f31421-234a-4525-941e-b0746f479124
https://github.com/user-attachments/assets/b48e712b-5bbf-4240-b4a9-35b1f784e7cc
기존에 `/landing`으로 되어있던 랜딩페이지 라우터를 로그인페이지와 동일하게 들어가도록 수정했어요.
랜딩페이지에 또 다른 주소가 붙는게 어색하다는 생각이 들어서 홈화면과 동일한 주소를 넣어주고 싶었는데,
1. 랜딩페이지는 로그인하지 않은 사용자만 보는 화면이라는 점
2. 홈으로 라우팅시키더라도 로그인을 하지 않은 사용자는 결국 로그인 페이지를 가장 먼저 보게된다는 점
을 고려해서 로그인과 동일한 주소를 갖도록 구현했어요.
다만, 로그아웃을 한 경우에는 랜딩페이지를 띄우지 않기로 했기 때문에, 로그인을 하지 않은 채로 서비스에 접속하여 로그인 페이지로 라우팅되는 경우에만 Navigate state를 함께 넘겨주어 지정한 state가 들어온 경우에만 랜딩페이지 라고 인식 -> 랜딩페이지를 띄워줍니다.
<br />
랜딩페이지를 확인해보니 3번 페이지에서 버튼을 클릭하면 4번 페이지 상단으로 이동해야 하는데, 중간 지점으로 이동하더라구요...!
이를 해결하기 위해 아래와 같은 로직을 설계했어요.
1. 4번 랜딩페이지 최상단 태그에 id를 부여
2. 해당 요소의 상단 위치 구하기
3. 3번 랜딩페이지의 버튼 클릭 시, 앞서 구한 위치보다 100만큼 적은 숫자에 해당하는 위치로 이동
<br />
랜딩페이지 …
> [ Hotfix ] 랜딩페이지 라우팅 및 디자인 QA 반영

- src/components/GroupCreate/LanguageSection.tsx
- src/constants/GroupCreate/LanguageConst.tsx
- src/libs/hooks/GroupEdit/usePatchRooms.ts
- src/page/GroupEdit.tsx
- close #302 
**초기값 설정**
https://github.com/user-attachments/assets/d492b86a-a077-42c5-98a5-9ed8a4f23fb5
**문제** 
- 새로고침을 하면 useGetDetail이 비동기로 동작하므로, 데이터 로딩 전에는 data가 undefined 상태로 들어왔습니다. 이 시점에서 initialData가 설정되어 빈 값이 들어왔습니다...
**해결**
- GroupEdit에서 데이터 로딩이 완료된 후에 inputs 상태를 설정하도록 수정
- 이를 위해 useEffect를 활용해 초기값을 동적으로 업데이트 했습니다.
**궁금한 점**
- useEffect를 사용해서 해결하는게 맞나요...?
```
useEffect(() => {
if (id && !isLoading) {
const {
title: groupTitle,
imageSrc,
capacity,
tags,
introduce,
information,
password,
} = data.data;
const initialData = {
title: groupTitle || '',
num: capacity ? capacity.toString() : '0',
secretKey: password || '',
intro: introduce || '',
group: information || '',
previewImage: imageSrc || null,
selectedTags: tags || '',
};
setInputs(initialData); …
```
>  [ Hotfix ] GroupEdit 뷰 데이터 로딩 완료 후 초기값 이슈, ALL 태그 다른게 들어오는 부분 이슈 해결

- src/components/Follower/Personal/ParticipatingGroup.tsx
- src/components/GroupAll/GroupItem.tsx
- src/components/PageLayout/PageLayout.tsx
- src/page/SolutionPage.tsx
- src/utils/removeSavedPage.ts
- close #316 
https://github.com/user-attachments/assets/1dd71a04-dfcb-4de4-aa12-43b413c8bdb4
기존 코드는 그룹을 정렬하는 부분의 초기값이 항상 '최신순'으로 정의되어 있었기 때문에, 그룹 전체보기 뷰에서 '가나다순'으로 필터링을 걸더라도 그룹 상세 뷰로 접근했다가 뒤로 돌아오면 '최신순'으로 바뀌어 있었어요.
이 부분이 사용자 입장에서 어색하다는 생각이 들어서 그룹 정렬을 선택한 경우, 그룹 상세 뷰로 넘어갔다 오더라도 정렬이 유지되도록 수정했어요.
수정한 로직은 아래와 같아요.
1. 그룹 전체 뷰에서 사용자가 선택한 정렬 값을 세션스토리지에 저장
2. 세션 스토리지에 저장된 값이 있다면 선택한 정렬 값을 저장하는 state의 값을 스토리지 값으로 정의
세션 스토리지에 저장된 값이 없다면 '최신순'으로 초기화
> [ Hotfix ] 레이아웃 깨지는 부분 수정 및 기능 디벨롭

- src/components/Calendar/Calendar.tsx
찾아보니 text 태그는 HTML5 이후부터 사용하지 않는 태그라고 하네요. 
출처 : [MDN](https://developer.mozilla.org/ko/docs/Web/HTML/Element/p)
> [ Hotfix ] p태그로 다시 변경 -> 웹페이지 접근성 측면에서 우위

- src/common/SolutionList/SavedSolutionList.tsx
- close #328 
https://github.com/user-attachments/assets/4e06f33d-8ef8-4249-939b-d7659730e7c0
재희가 문제풀이 다시보기 뷰 리스트에서 7개의 문제를 하나의 리스트로 요청하고 있는데, 5개만 나오고 있다고 알려주어서 코드를 확인해보았어요.
문제 리스트가 저장된 배열을 확인해보니, 화면에 렌더링되던 것처럼 5개의 리스트만 보여지고 있더라구요.
문제풀이 리스트를 보여주는 뷰에서 모두 `SavedSolutionList`를 사용하고 있고 `isSmallList`라는 Props를 활용해서 화면에 보여줄 문제풀이 수를 조절해요. 그런데 문제 리스트를 저장하고 있는 배열에서 isSmallList 값과 관계없이, 서버에서 받아온 문제 리스트의 수가 5개를 넘어가면 무조건 5개로 잘라서 보여주고 있었어요.
실제 기획, 디자인과 동일하게 구현하기 위해 문제 리스트를 저장하는 배열을 정의할 때 isSmallList 관련 조건을 추가하여 isSmallList가 true인 경우에만 문제 수를 5개로 제한해서 이슈를 해결했어요.
> [ Hotfix ] 문제풀이 리스트 수가 지정한 것과 다르게 나오는 이슈 해결

- src/common/RecommendCard.tsx
- close #issue_number
사파리환경 CSS 
```jsx
const CardContent = styled.p`
display: -webkit-box;
-webkit-line-clamp: 2;
-webkit-box-orient: vertical;
/* overflow: hidden; */
text-overflow: ellipsis;
height: 5.3rem;
color: ${({ theme }) => theme.colors.gray300};
${({ theme }) => theme.fonts.body_ligth_12};
flex: 1;
`;
```
여기서   ```display: -webkit-box : CSS```속성은 블록 컨테이너의 콘텐츠를 지정한 줄 수만큼으로 제한합니다.
`display` 속성을 `-webkit-box` 또는 `-webkit-inline-box`로, 그리고 `-webkit-box-orient` 속성을 `vertical`로 설정한 경우에만 동작한다고 하네요.
여기서 문제되는 점은 overflow : hidden입니다
`-webkit-line-clamp`만 사용하는 경우, 말줄임표는 노출되나 넘친 콘텐츠가 숨겨지지 않으므로 대개 `overflow` 속성 또한 `hidden`으로 설정해야 한다고 합니다.
출처 -> [📎Mdn](https://developer.mozilla.org/ko/docs/Web/CSS/-webkit-line-clamp)
> [Refactor] 사파리환경에서 CSS 안보이던 현상 수정

- src/common/SolutionList/ListFilter.tsx
- src/common/SolutionList/SavedSolutionList.tsx
- src/components/Calendar/Calendar.tsx
- close #335 
https://github.com/user-attachments/assets/ce02a1dd-733d-455b-a95e-b4fb036436e2
https://github.com/user-attachments/assets/8a2f0c54-9a52-4195-b561-a85d3e352675
홈 화면과 저장된 문제풀일 리스트를 보여주는 화면 모두 클릭된 년도가 아닌, `현재 년도`가 unsolvedMonth api의 year로 넘어가고 있어서 클릭된 년도가 바뀌어도 최신 정보가 들어가지 않는 것이 문제였어요.
홈화면에서는 간단히 currentYear를 정의하고 있는 변수를 삭제하고 props로 받아오고 있던 clickedYear를 unsolvedMonth api의 year 정보로 넘겨주는 것으로 문제를 해결했어요.
다만, 저장된 문제풀이 리스트 화면은 코드가 조금 더 복잡했어요. 
클릭된 년도와 월 정보를 하나의 state로 관리하고 있었고, 특히 클릭된 월 정보의 초기값은 unsolvedMonth api에 의존하고 있었기 때문에, 해당 state를 unsolvedMonth api 보다 먼저 정의하여 api의 year에 클릭된 년도를 넘겨주는 방식은 사용할 수 없었어요.
따라서 클릭된 년도와 월 정보를 각각 독립적인 state로 분리했어요. 두 state 모두 기존과 동일하게 값을 초기화하되, 클릭된 년도 state는 unsolvedMonth api를 호출하기 전에 정의하여 해당 api의 year 정보로 넘겨주어 문제를 해결했어요.
클릭된 월 state는 기존과 동일하게 …
> [ Hofix ] 년도가 바꼈을 때 해당 년도에 저장된 문제풀이 정보가 나오지 않는 이슈 해결

- src/PrivateRoute.tsx
- src/Router.tsx
- src/page/Home.tsx
- src/page/LoginPage.tsx
- src/page/SolutionListPage.tsx
- close #342 
이전에 로그인 하지 않은 페이지에 대해서 Reactquery의 ErrorBoundary로 로그인 페이지로 라우팅을 시켜주어서 로그인 분기처리를 했었는데요..! 시간이 지날수록 에러 바운더리에서 처리했던건 말 그대로 에러 관련 처리를 했을 뿐, 원래 구현하려 했던 로그인 분기처리가 아닌 것 같다는 생각이 들었어요.
그러던 중 api 통신이 없는 페이지에서는 로그인 없이 접근해도 에러가 발생하지 않기 때문에, 또 다시 이전과 같은 레이아웃 깨짐 현상이 나타난다는 것을 알게 되었어요.
세션 스토리지에서 관리하는 토큰 값과 useNavigate를 활용해서 로그인 분기처리를 해주려고 했으나, App이나 Route 같은 상위 컴포넌트에서는 useNavigate로 라우터를 이동시킬 수 없어 적절한 방법은 아니였어요.
또, 각각의 컴포넌트에서 로그인 여부를 판단하고 그에 따라 분기할 수도 있었지만, 중복코드가 너무 많이 발생하고 있었고 모든 컴포넌트에서 동일한 동작을 매번 수행하는 것이 효율적인 방법은 아니라고 판단했어요.
그래서 전역적인 라우터 관리를 위해 token 값을 활용하여 로그인 여부를 판단하는 PrivateRoute라는 컴포넌트를 하나 만들었어요.
PrivateRoute는 토큰으로 로그인 여부를 판단, 로그인을 하지 않은 상태라면 로그인 페이지를 반환하고 로그인을 한 상태라면 Outlet을 반환해요. 
하지만 예외적으로 홈 컴포넌트에서는 로그인을 하지 않았다면 랜딩페이지를 띄워줘야 했기 때문에, nullable props를 활용하여 해당 값이 true일 때를 예외적인 상황으로 판단해서 …
> [ Refactor ] 로그인하지 않은 페이지로 접근 시, 로그인 페이지로 라우팅 (+ 랜딩페이지 주소 변경) 

- src/common/InformationTooltip.tsx
- src/components/Admin/GroupStatistics/NumOfMembers.tsx
- src/components/GroupAll/GroupRecommend.tsx
- src/components/GroupCreate/ImageSection.tsx
- src/components/Home/TodaySolve.tsx
- src/components/Home/WeekRate.tsx
- src/components/Register/Repositories.tsx
- close #349 
1. 폰트 사이즈 수정
2. 홈 화면에 오늘 문제풀이 툴팁도 아래 방식으로 수정했습니다. 
```
<Tooltip>
목표설정은 우측 상단 닉네임 {'>'} 내 프로필
<ToolTipNextLine>{'>'} 나의 목표에서 설정 가능해요</ToolTipNextLine>
```
```
<ToolTipNextLine>
목표설정은 우측 상단 닉네임 {'>'} 내 프로필
</ToolTipNextLine>
<ToolTipNextLine>{'>'} 나의 목표에서 설정 가능해요</ToolTipNextLine>
```
> [ Hotfix ] 폰트 정의 방법 수정

- src/common/DetailTooltip.tsx
- src/common/TooltipInfo.tsx
- src/components/GroupCreate/ImageSection.tsx
- src/components/Home/WeekRate.tsx
- src/components/Register/Repositories.tsx
- close #347 
필요한 props를 전달해서 사용할 수 있게 분리해뒀습니다!
```
const TooltipInfo = ({ isVisible, onClick, text }: TooltipProps) => {
return (
<TooltipContainer $isVisible={isVisible}>
<Text>{text}</Text>
<TooltipClose type="button" onClick={onClick}>
<IcCancelSmallWhite />
</TooltipClose>
</TooltipContainer>
);
};
```
```
<TooltipInfo
isVisible={isTooltipVisible}
onClick={handleTooltipClose}
text="주간 성과율은 월요일마다 초기화 돼요"
/>
```
1. `InformationTooltip` 공통 컴포넌트가 있더라구요.  툴팁 코드들이 반복되고 있기 때문에 `InformationTooltip` 이용해서 수정할 예정입니다. 
2. font-size 수정
font-size: ${({ theme }) => theme.fonts.body_ligth_12}; => 이렇게 정의 되어있는 부분들이 있어서 수정할 예정입니다.
> [ Refactor ] 툴팁 공통 컴포넌트로 분리

- src/common/CommonUserList.tsx
- src/common/Gnb.tsx
- src/common/Groups.tsx
- src/common/RecommendCard.tsx
- src/common/SolutionList/SavedSolution.tsx
- src/common/SolutionList/SavedSolutionList.tsx
- src/components/Follower/Current/AdditionalProblemsModal.tsx
- src/components/Follower/Personal/ParticipatingGroup.tsx
- src/components/GroupAll/GroupItem.tsx
- src/components/Home/WeekFollowing/WeeklyFollower.tsx
- src/components/MyGroup/ActiveGroups.tsx
- src/components/MyGroup/PersonalGroup.tsx
- src/components/PageLayout/PageLayout.tsx
- src/libs/hooks/Alarm/usePostAlarmRead.ts
- src/libs/hooks/GroupEdit/usePatchRooms.ts
- src/libs/hooks/GroupJoin/usePostAnswer.ts
- src/page/GroupComplete.tsx
- src/page/GroupEdit.tsx
- src/types/Follower/Current/currentType.ts
- src/types/GroupAll/RecommendCardType.ts
- src/types/MyGroup/myGroupType.ts
- src/types/Solution/solutionTypes.ts
- src/utils/handleClickPage.ts
- src/utils/removeSavedPage.ts
- close #362 
https://github.com/user-attachments/assets/80b47649-4b41-47be-9af4-45206500dd0c
<br />
예전에 기능 개발할 때 선택한 페이지가 뒤로 가기를 했을 때도 유지되게 하기 위해서 session storage를 사용했었어요. 추가 개발을 진행하며 관련 로직이 꼬여있는 것을 확인해서 session storage로 관리하던 페이지 정보를 모두 제거했어요.
(ex. a 페이지에서 2페이지 선택 후 b 페이지로 이동 -> b 페이지에 처음 접근했음에도 페이지 선택이 2페이지로 되어 있는 것을 확인)
선택한 페이지를 관리하는 기능이 없다보니, 페이지를 선택하고 상세뷰로 접근했다가 뒤로 가기 버튼을 클릭했을 때 이전에 접근한 페이지가 아닌 첫번째 페이지로 초기화되어 사용자 입장에서 매우매우 불편하고 불친절하게 느껴졌어요. 여러 사이트를 경험하다 보니 보통은 선택한 페이지나 년도, 레벨 등 보안이 중요하지 않은 정보는 query string으로 처리하는 것을 알 수 있었어요. 
기존에 구현해둔 라우터를 수정하지 않아도 되고, 각 페이지마다 정보를 따로 관리하니 이전처럼 로직이 꼬이지 않는다는 장점이 있어 해당 방법을 선택했어요. 이렇게 구현하니 불필요한 props나 state 정의 부분이 발생해서 해당 부분은 모두 제거해주었어요.  
또한, 화살표 버튼이나 숫자 클릭으로 페이지를 이동하는 함수 로직이 중복되는 경우가 많아서 해당 부분은 유틸로 분리해주었어요!
추후 사용자가 선택한 년도와 정렬(최신순, 오래된순, 가나다순 등) 부분도 …
> [ SP2 ] 특정 페이지 선택 -> 상세 뷰로 이동한 후, 뒤로 가기 시 기존 페이지로 복원되는 기능 구현

- package.json
- src/components/GroupCreate/ImageSection.tsx
- src/page/GroupCreate.tsx
- src/page/GroupEdit.tsx
- yarn.lock
- close #366 
이미지를 압축하지 않고 원본 파일 그대로 업로드하는 방식으로 인해 이미지 로딩 속도가 저하 됐고 렌더링 시간이 증가하는 문제점을 발견했습니다. 위와 같은 문제를 해결하기 위해 클라에서 먼저 이미지를 압축한 후 업로드하는 방식으로 변경해서 구현했습니다.
```
const options = {
maxSizeMB: 0.2, // 압축된 이미지의 최대 크기를 0.2MB로 제한
maxWidthOrHeight: 1224, // 이미지의 최대 너비 또는 높이를 1224px로 제한
useWebWorker: true, // 웹 워커를 사용하여 메인 스레드 성능 저하 방지
};
```
- maxSizeMB 0.2로 설정해준 이유는 게시글 이미지 권장 크기는 100~200KB라서 0.2로 설정해줬습니다.
- 처음에는 그룹 페이지에서 보여지는 이미지 크기( 297 × 178 px)를 기준으로 약 2배 크기인 594px로 설정하였습니다. 하지만, 그룹 정보 보기 뷰에서 해당 이미지를 표시할 때 해상도가 낮아져 이미지가 깨지는 문제가 발생하였습니다. 이를 해결하기 위해, 그룹 정보 보기 뷰에서 사용하는 이미지 크기( 612 × 368 px)를 기준으로 1224px로 설정해 줬습니다.
```
const compressedBlob = await imageCompression(file, options);
const compressedFile = new File([compressedBlob], file.name, {
type: file.type,
lastModified: Date.now(),
});
``` …
> [ SP2 ] 이미지 리사이징
